### ISSUE TITLE
Wrong Astro Link

### ISSUE THREAD

**Issue by demonarch** [Athena-OS/athena-docs#29]
Hi there,
I hope you're doing great, I'm a fan of your work and admire what you do.

This is to inform you that in src/components/TOC.astro:12 you have written wrong url to Astro. Astro (The Web framework) is addressed at "https://astro.build/". I wouldn't open this issue if the svg wasn't representing their logo.

Good luck with all you do, I'm waiting until your project reaches to a more stable release, so I can install it even on my fridge! HaHa. Arch for life! and you're making a very good one of it!

Regards,
demonarch

**Comment by D3vil0p3r** [comment]
Hey @demonarch Thank you for opening this ticket.

Currently I'm outside and I take care of it once I back home the next week.

About Athena Arch, it is a rolling release, so you can try to start to install on some machine also to try and check if it is what you expected.

Of course there is a lot of tasks to do that I aim to complete ^^

UP: I commited the fix by my phone. It should work in 1 minute. Thanks for reporting!

**Comment by demonarch** [comment]
Hey @D3vil0p3r !
Thanks for the fix and quick response.

I have already tried it by using it as my main for 2 months. was very cool. I'll keep trying it once in a while to follow the progress. Good luck mate!

**Comment by demonarch** [comment]
Confirmed the fix on live website.

**Comment by D3vil0p3r** [comment]
> Hey @D3vil0p3r !
> Thanks for the fix and quick response.
> 
> I have already tried it by using it as my main for 2 months. was very cool. I'll keep trying it once in a while to follow the progress. Good luck mate!

What was the concern or issue that does not allow you to use it as main now?

**Comment by demonarch** [comment]
> > Hey @D3vil0p3r !
> > Thanks for the fix and quick response.
> > I have already tried it by using it as my main for 2 months. was very cool. I'll keep trying it once in a while to follow the progress. Good luck mate!
> 
> What was the concern or issue that does not allow you to use it as main now?

@D3vil0p3r I believe that it has not been tested on a wide range of devices to make sure of delivering same functionality and experience on different machines, maybe I'm wrong but this was my conclusion after installing on few. by these differences I mean sometimes not being able to reach a point of being able to do a manual fix. That's it.

**Comment by D3vil0p3r** [comment]
I agree. If you have a proposal to manage it, it is welcome.

**Comment by demonarch** [comment]
@D3vil0p3r awesome, I will contact you to discuss it.
